---
# tasks file for master
- name: Install kubectl 
  apt:
    name: kubectl=1.14.0-00
    state: present
    force: yes
- name: Initialize the cluster
  shell: 
    cmd: kubeadm init --pod-network-cidr={{ network_cidr }} >> cluster_initialized.txt
    chdir: /home/ubuntu/
    creates: cluster_initialized.txt
- name: Create .kube directory
  become: yes
  become_user: ubuntu
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755
    owner: ubuntu
    group: ubuntu
- name: Copy admin.conf to $HOME/.kube
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu
- name: Install Pod Network
  become: yes
  become_user: ubuntu
  shell:
    cmd: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network.txt
    chdir: $HOME
    creates: pod_network.txt
- name: Get join command
  shell:
    cmd: kubeadm token create --print-join-command
  register: join_command_raw
- name: Set_fact join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}" 
#- name: Debug fact
#  debug: msg={{ hostvars[groups['k8s-master'][0]].join_command }}
